import type { PiDesktopApi } from "../../shared/preload-api";
import { err } from "../../shared/result";

export const createUnavailablePiDesktopApi = (message: string): PiDesktopApi => {
	const unavailable = async () => err("app_transport.unavailable", message);

	return {
		app: {
			getVersion: unavailable,
			openExternal: unavailable,
		},
		project: {
			getState: unavailable,
			createFromScratch: unavailable,
			addExistingFolder: unavailable,
			select: unavailable,
			rename: unavailable,
			remove: unavailable,
			openInFinder: unavailable,
			locateFolder: unavailable,
			setPinned: unavailable,
			getGitSettings: unavailable,
			setGitSettings: unavailable,
			checkAvailability: unavailable,
		},
		chat: {
			create: unavailable,
			createStandalone: unavailable,
			select: unavailable,
			rename: unavailable,
			selectStandalone: unavailable,
			fork: unavailable,
			clone: unavailable,
			branch: unavailable,
		},
		workspaceFiles: {
			listDirectory: unavailable,
			readFile: unavailable,
			writeFile: unavailable,
		},
		sourceControl: {
			getStatus: unavailable,
			checkIgnored: unavailable,
			stage: unavailable,
			unstage: unavailable,
			discard: unavailable,
			bulkStage: unavailable,
			bulkUnstage: unavailable,
			bulkDiscard: unavailable,
			initializeRepository: unavailable,
			commit: unavailable,
			getDiff: unavailable,
			getUpstreamStatus: unavailable,
			fetch: unavailable,
			push: unavailable,
			forcePushWithLease: unavailable,
			pull: unavailable,
			sync: unavailable,
			fastForward: unavailable,
			publish: unavailable,
			rebaseFromBase: unavailable,
			getBranchCompare: unavailable,
			getHistory: unavailable,
			getCommitFiles: unavailable,
			abortConflict: unavailable,
			createPullRequest: unavailable,
			getPullRequestInfo: unavailable,
			getGhAuthStatus: unavailable,
			generateCommitMessage: unavailable,
			generatePullRequestFields: unavailable,
			cancelGeneration: unavailable,
		},
		clipboard: {
			writeText: unavailable,
		},
		piSession: {
			start: unavailable,
			submit: unavailable,
			abort: unavailable,
			history: unavailable,
			prepare: unavailable,
			attach: unavailable,
			dispose: unavailable,
			getSettings: unavailable,
			getDefaultSettings: unavailable,
			getCommands: unavailable,
			setModel: unavailable,
			setThinkingLevel: unavailable,
			setDefaultModel: unavailable,
			setDefaultThinkingLevel: unavailable,
			updateQueuedMessage: unavailable,
			removeQueuedMessage: unavailable,
			onEvent: () => () => {},
		},
	};
};
