import { z } from "zod";
import {
	AppVersionResultSchema,
	ChatBranchInputSchema,
	ChatCloneInputSchema,
	ChatCreateInputSchema,
	ChatForkInputSchema,
	ChatRenameInputSchema,
	ChatStandaloneCreateInputSchema,
	ChatSelectionInputSchema,
	ChatStandaloneSelectionInputSchema,
	PiSessionAbortInputSchema,
	PiSessionActionResultSchema,
	PiSessionAttachInputSchema,
	PiSessionPrepareInputSchema,
	PiSessionDisposeInputSchema,
	PiSessionEventSchema,
	PiSessionGetDefaultSettingsInputSchema,
	PiSessionGetRuntimeCommandsInputSchema,
	PiSessionGetSettingsInputSchema,
	PiSessionHistoryInputSchema,
	PiSessionHistoryResultSchema,
	PiSessionQueueResultSchema,
	PiSessionRemoveQueuedMessageInputSchema,
	PiSessionRuntimeCommandsResultSchema,
	PiSessionSetDefaultModelInputSchema,
	PiSessionSetDefaultThinkingLevelInputSchema,
	PiSessionSetModelInputSchema,
	PiSessionSetThinkingLevelInputSchema,
	PiSessionSettingsResultSchema,
	PiSessionStartInputSchema,
	PiSessionStartResultSchema,
	PiSessionSubmitInputSchema,
	PiSessionUpdateQueuedMessageInputSchema,
	ProjectIdInputSchema,
	ProjectPinnedInputSchema,
	ProjectRenameInputSchema,
	ProjectStateViewResultSchema,
	WorkspaceFilesPathInputSchema,
	WorkspaceFilesWriteInputSchema,
	WorkspaceListDirectoryResultSchema,
	WorkspaceReadFileResultSchema,
	WorkspaceWriteFileResultSchema,
	SourceControlBulkPathsInputSchema,
	SourceControlCheckIgnoredResultSchema,
	SourceControlGetStatusResultSchema,
	SourceControlMutationResultSchema,
	SourceControlPathInputSchema,
	SourceControlProjectInputSchema,
} from "./ipc";

export const AppRpcRequestSchema = z.discriminatedUnion("operation", [
	z.strictObject({ operation: z.literal("app.getVersion"), input: z.undefined().optional() }),
	z.strictObject({ operation: z.literal("project.getState"), input: z.undefined().optional() }),
	z.strictObject({ operation: z.literal("project.createFromScratch"), input: z.undefined().optional() }),
	z.strictObject({ operation: z.literal("project.addExistingFolder"), input: z.undefined().optional() }),
	z.strictObject({ operation: z.literal("project.select"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("project.rename"), input: ProjectRenameInputSchema }),
	z.strictObject({ operation: z.literal("project.remove"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("project.openInFinder"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("project.locateFolder"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("project.setPinned"), input: ProjectPinnedInputSchema }),
	z.strictObject({ operation: z.literal("project.checkAvailability"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("chat.create"), input: ChatCreateInputSchema }),
	z.strictObject({ operation: z.literal("chat.createStandalone"), input: ChatStandaloneCreateInputSchema }),
	z.strictObject({ operation: z.literal("chat.select"), input: ChatSelectionInputSchema }),
	z.strictObject({ operation: z.literal("chat.rename"), input: ChatRenameInputSchema }),
	z.strictObject({ operation: z.literal("chat.selectStandalone"), input: ChatStandaloneSelectionInputSchema }),
	z.strictObject({ operation: z.literal("chat.fork"), input: ChatForkInputSchema }),
	z.strictObject({ operation: z.literal("chat.clone"), input: ChatCloneInputSchema }),
	z.strictObject({ operation: z.literal("chat.branch"), input: ChatBranchInputSchema }),
	z.strictObject({ operation: z.literal("piSession.start"), input: PiSessionStartInputSchema }),
	z.strictObject({ operation: z.literal("piSession.submit"), input: PiSessionSubmitInputSchema }),
	z.strictObject({ operation: z.literal("piSession.abort"), input: PiSessionAbortInputSchema }),
	z.strictObject({ operation: z.literal("piSession.history"), input: PiSessionHistoryInputSchema }),
	z.strictObject({ operation: z.literal("piSession.prepare"), input: PiSessionPrepareInputSchema }),
	z.strictObject({ operation: z.literal("piSession.attach"), input: PiSessionAttachInputSchema }),
	z.strictObject({ operation: z.literal("piSession.dispose"), input: PiSessionDisposeInputSchema }),
	z.strictObject({ operation: z.literal("piSession.getSettings"), input: PiSessionGetSettingsInputSchema }),
	z.strictObject({ operation: z.literal("piSession.getCommands"), input: PiSessionGetRuntimeCommandsInputSchema }),
	z.strictObject({
		operation: z.literal("piSession.getDefaultSettings"),
		input: PiSessionGetDefaultSettingsInputSchema,
	}),
	z.strictObject({ operation: z.literal("piSession.setModel"), input: PiSessionSetModelInputSchema }),
	z.strictObject({ operation: z.literal("piSession.setThinkingLevel"), input: PiSessionSetThinkingLevelInputSchema }),
	z.strictObject({ operation: z.literal("piSession.setDefaultModel"), input: PiSessionSetDefaultModelInputSchema }),
	z.strictObject({
		operation: z.literal("piSession.setDefaultThinkingLevel"),
		input: PiSessionSetDefaultThinkingLevelInputSchema,
	}),
	z.strictObject({
		operation: z.literal("piSession.updateQueuedMessage"),
		input: PiSessionUpdateQueuedMessageInputSchema,
	}),
	z.strictObject({
		operation: z.literal("piSession.removeQueuedMessage"),
		input: PiSessionRemoveQueuedMessageInputSchema,
	}),
	z.strictObject({
		operation: z.literal("workspaceFiles.listDirectory"),
		input: WorkspaceFilesPathInputSchema,
	}),
	z.strictObject({
		operation: z.literal("workspaceFiles.readFile"),
		input: WorkspaceFilesPathInputSchema,
	}),
	z.strictObject({
		operation: z.literal("workspaceFiles.writeFile"),
		input: WorkspaceFilesWriteInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.getStatus"),
		input: SourceControlProjectInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.checkIgnored"),
		input: SourceControlBulkPathsInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.stage"),
		input: SourceControlPathInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.unstage"),
		input: SourceControlPathInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.discard"),
		input: SourceControlPathInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.bulkStage"),
		input: SourceControlBulkPathsInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.bulkUnstage"),
		input: SourceControlBulkPathsInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.bulkDiscard"),
		input: SourceControlBulkPathsInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.initializeRepository"),
		input: SourceControlProjectInputSchema,
	}),
]);

export type AppRpcRequest = z.infer<typeof AppRpcRequestSchema>;
export type AppRpcOperation = AppRpcRequest["operation"];

export const AppRpcResponseSchemas = {
	"app.getVersion": AppVersionResultSchema,
	"project.getState": ProjectStateViewResultSchema,
	"project.createFromScratch": ProjectStateViewResultSchema,
	"project.addExistingFolder": ProjectStateViewResultSchema,
	"project.select": ProjectStateViewResultSchema,
	"project.rename": ProjectStateViewResultSchema,
	"project.remove": ProjectStateViewResultSchema,
	"project.openInFinder": ProjectStateViewResultSchema,
	"project.locateFolder": ProjectStateViewResultSchema,
	"project.setPinned": ProjectStateViewResultSchema,
	"project.checkAvailability": ProjectStateViewResultSchema,
	"chat.create": ProjectStateViewResultSchema,
	"chat.createStandalone": ProjectStateViewResultSchema,
	"chat.select": ProjectStateViewResultSchema,
	"chat.rename": ProjectStateViewResultSchema,
	"chat.selectStandalone": ProjectStateViewResultSchema,
	"chat.fork": ProjectStateViewResultSchema,
	"chat.clone": ProjectStateViewResultSchema,
	"chat.branch": ProjectStateViewResultSchema,
	"piSession.start": PiSessionStartResultSchema,
	"piSession.submit": PiSessionActionResultSchema,
	"piSession.abort": PiSessionActionResultSchema,
	"piSession.history": PiSessionHistoryResultSchema,
	"piSession.prepare": PiSessionStartResultSchema,
	"piSession.attach": PiSessionStartResultSchema,
	"piSession.dispose": PiSessionActionResultSchema,
	"piSession.getSettings": PiSessionSettingsResultSchema,
	"piSession.getCommands": PiSessionRuntimeCommandsResultSchema,
	"piSession.getDefaultSettings": PiSessionSettingsResultSchema,
	"piSession.setModel": PiSessionSettingsResultSchema,
	"piSession.setThinkingLevel": PiSessionSettingsResultSchema,
	"piSession.setDefaultModel": PiSessionSettingsResultSchema,
	"piSession.setDefaultThinkingLevel": PiSessionSettingsResultSchema,
	"piSession.updateQueuedMessage": PiSessionQueueResultSchema,
	"piSession.removeQueuedMessage": PiSessionQueueResultSchema,
	"workspaceFiles.listDirectory": WorkspaceListDirectoryResultSchema,
	"workspaceFiles.readFile": WorkspaceReadFileResultSchema,
	"workspaceFiles.writeFile": WorkspaceWriteFileResultSchema,
	"sourceControl.getStatus": SourceControlGetStatusResultSchema,
	"sourceControl.checkIgnored": SourceControlCheckIgnoredResultSchema,
	"sourceControl.stage": SourceControlMutationResultSchema,
	"sourceControl.unstage": SourceControlMutationResultSchema,
	"sourceControl.discard": SourceControlMutationResultSchema,
	"sourceControl.bulkStage": SourceControlMutationResultSchema,
	"sourceControl.bulkUnstage": SourceControlMutationResultSchema,
	"sourceControl.bulkDiscard": SourceControlMutationResultSchema,
	"sourceControl.initializeRepository": SourceControlMutationResultSchema,
} as const satisfies Record<AppRpcOperation, z.ZodTypeAny>;

export const PiSessionEventEnvelopeSchema = z.strictObject({
	type: z.literal("pi-session:event"),
	event: PiSessionEventSchema,
});

export type PiSessionEventEnvelope = z.infer<typeof PiSessionEventEnvelopeSchema>;
