import { z } from "zod";
import {
	AppVersionResultSchema,
	ChatBranchInputSchema,
	ChatCloneInputSchema,
	ChatCreateInputSchema,
	ChatForkInputSchema,
	ChatRenameInputSchema,
	ChatStandaloneCreateInputSchema,
	ChatSelectionInputSchema,
	ChatStandaloneSelectionInputSchema,
	PiSessionAbortInputSchema,
	PiSessionActionResultSchema,
	PiSessionAttachInputSchema,
	PiSessionPrepareInputSchema,
	PiSessionDisposeInputSchema,
	PiSessionEventSchema,
	PiSessionGetDefaultSettingsInputSchema,
	PiSessionGetRuntimeCommandsInputSchema,
	PiSessionGetSettingsInputSchema,
	PiSessionHistoryInputSchema,
	PiSessionHistoryResultSchema,
	PiSessionQueueResultSchema,
	PiSessionRemoveQueuedMessageInputSchema,
	PiSessionRuntimeCommandsResultSchema,
	PiSessionSetDefaultModelInputSchema,
	PiSessionSetDefaultThinkingLevelInputSchema,
	PiSessionSetModelInputSchema,
	PiSessionSetThinkingLevelInputSchema,
	PiSessionSettingsResultSchema,
	PiSessionStartInputSchema,
	PiSessionStartResultSchema,
	PiSessionSubmitInputSchema,
	PiSessionUpdateQueuedMessageInputSchema,
	ProjectGitSettingsInputSchema,
	ProjectGitSettingsResultSchema,
	ProjectIdInputSchema,
	ProjectPinnedInputSchema,
	ProjectRenameInputSchema,
	ProjectStateViewResultSchema,
	OpenExternalInputSchema,
	OpenExternalResultSchema,
	WorkspaceFilesPathInputSchema,
	WorkspaceFilesWriteInputSchema,
	WorkspaceListDirectoryResultSchema,
	WorkspaceReadFileResultSchema,
	WorkspaceWriteFileResultSchema,
	SourceControlBulkDiscardInputSchema,
	SourceControlBulkPathsInputSchema,
	SourceControlCheckIgnoredResultSchema,
	SourceControlCommitInputSchema,
	SourceControlCommitResultSchema,
	SourceControlCreatePullRequestInputSchema,
	SourceControlCancelGenerationInputSchema,
	SourceControlGenerateCommitMessageResultSchema,
	SourceControlGeneratePullRequestFieldsInputSchema,
	SourceControlGeneratePullRequestFieldsResultSchema,
	SourceControlGenerationRequestInputSchema,
	SourceControlDiscardInputSchema,
	SourceControlBranchCompareInputSchema,
	SourceControlBranchCompareResultSchema,
	SourceControlGetCommitFilesInputSchema,
	SourceControlGetCommitFilesResultSchema,
	SourceControlGetDiffInputSchema,
	SourceControlGetHistoryInputSchema,
	SourceControlGetHistoryResultSchema,
	SourceControlGetDiffResultSchema,
	SourceControlGetStatusResultSchema,
	SourceControlMutationResultSchema,
	SourceControlPathInputSchema,
	SourceControlProjectInputSchema,
	SourceControlRebaseInputSchema,
	SourceControlRemoteActionInputSchema,
	SourceControlAbortConflictInputSchema,
	SourceControlPullRequestInfoResultSchema,
	SourceControlGhAuthStatusResultSchema,
	SourceControlUpstreamStatusResultSchema,
} from "./ipc";

export const AppRpcRequestSchema = z.discriminatedUnion("operation", [
	z.strictObject({ operation: z.literal("app.getVersion"), input: z.undefined().optional() }),
	z.strictObject({ operation: z.literal("app.openExternal"), input: OpenExternalInputSchema }),
	z.strictObject({ operation: z.literal("project.getState"), input: z.undefined().optional() }),
	z.strictObject({ operation: z.literal("project.createFromScratch"), input: z.undefined().optional() }),
	z.strictObject({ operation: z.literal("project.addExistingFolder"), input: z.undefined().optional() }),
	z.strictObject({ operation: z.literal("project.select"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("project.rename"), input: ProjectRenameInputSchema }),
	z.strictObject({ operation: z.literal("project.remove"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("project.openInFinder"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("project.locateFolder"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("project.setPinned"), input: ProjectPinnedInputSchema }),
	z.strictObject({ operation: z.literal("project.getGitSettings"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("project.setGitSettings"), input: ProjectGitSettingsInputSchema }),
	z.strictObject({ operation: z.literal("project.checkAvailability"), input: ProjectIdInputSchema }),
	z.strictObject({ operation: z.literal("chat.create"), input: ChatCreateInputSchema }),
	z.strictObject({ operation: z.literal("chat.createStandalone"), input: ChatStandaloneCreateInputSchema }),
	z.strictObject({ operation: z.literal("chat.select"), input: ChatSelectionInputSchema }),
	z.strictObject({ operation: z.literal("chat.rename"), input: ChatRenameInputSchema }),
	z.strictObject({ operation: z.literal("chat.selectStandalone"), input: ChatStandaloneSelectionInputSchema }),
	z.strictObject({ operation: z.literal("chat.fork"), input: ChatForkInputSchema }),
	z.strictObject({ operation: z.literal("chat.clone"), input: ChatCloneInputSchema }),
	z.strictObject({ operation: z.literal("chat.branch"), input: ChatBranchInputSchema }),
	z.strictObject({ operation: z.literal("piSession.start"), input: PiSessionStartInputSchema }),
	z.strictObject({ operation: z.literal("piSession.submit"), input: PiSessionSubmitInputSchema }),
	z.strictObject({ operation: z.literal("piSession.abort"), input: PiSessionAbortInputSchema }),
	z.strictObject({ operation: z.literal("piSession.history"), input: PiSessionHistoryInputSchema }),
	z.strictObject({ operation: z.literal("piSession.prepare"), input: PiSessionPrepareInputSchema }),
	z.strictObject({ operation: z.literal("piSession.attach"), input: PiSessionAttachInputSchema }),
	z.strictObject({ operation: z.literal("piSession.dispose"), input: PiSessionDisposeInputSchema }),
	z.strictObject({ operation: z.literal("piSession.getSettings"), input: PiSessionGetSettingsInputSchema }),
	z.strictObject({ operation: z.literal("piSession.getCommands"), input: PiSessionGetRuntimeCommandsInputSchema }),
	z.strictObject({
		operation: z.literal("piSession.getDefaultSettings"),
		input: PiSessionGetDefaultSettingsInputSchema,
	}),
	z.strictObject({ operation: z.literal("piSession.setModel"), input: PiSessionSetModelInputSchema }),
	z.strictObject({ operation: z.literal("piSession.setThinkingLevel"), input: PiSessionSetThinkingLevelInputSchema }),
	z.strictObject({ operation: z.literal("piSession.setDefaultModel"), input: PiSessionSetDefaultModelInputSchema }),
	z.strictObject({
		operation: z.literal("piSession.setDefaultThinkingLevel"),
		input: PiSessionSetDefaultThinkingLevelInputSchema,
	}),
	z.strictObject({
		operation: z.literal("piSession.updateQueuedMessage"),
		input: PiSessionUpdateQueuedMessageInputSchema,
	}),
	z.strictObject({
		operation: z.literal("piSession.removeQueuedMessage"),
		input: PiSessionRemoveQueuedMessageInputSchema,
	}),
	z.strictObject({
		operation: z.literal("workspaceFiles.listDirectory"),
		input: WorkspaceFilesPathInputSchema,
	}),
	z.strictObject({
		operation: z.literal("workspaceFiles.readFile"),
		input: WorkspaceFilesPathInputSchema,
	}),
	z.strictObject({
		operation: z.literal("workspaceFiles.writeFile"),
		input: WorkspaceFilesWriteInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.getStatus"),
		input: SourceControlProjectInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.checkIgnored"),
		input: SourceControlBulkPathsInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.stage"),
		input: SourceControlPathInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.unstage"),
		input: SourceControlPathInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.discard"),
		input: SourceControlDiscardInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.bulkStage"),
		input: SourceControlBulkPathsInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.bulkUnstage"),
		input: SourceControlBulkPathsInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.bulkDiscard"),
		input: SourceControlBulkDiscardInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.initializeRepository"),
		input: SourceControlProjectInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.commit"),
		input: SourceControlCommitInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.getDiff"),
		input: SourceControlGetDiffInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.getUpstreamStatus"),
		input: SourceControlProjectInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.fetch"),
		input: SourceControlRemoteActionInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.push"),
		input: SourceControlRemoteActionInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.forcePushWithLease"),
		input: SourceControlRemoteActionInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.pull"),
		input: SourceControlRemoteActionInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.sync"),
		input: SourceControlRemoteActionInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.fastForward"),
		input: SourceControlRemoteActionInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.publish"),
		input: SourceControlRemoteActionInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.rebaseFromBase"),
		input: SourceControlRebaseInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.getBranchCompare"),
		input: SourceControlBranchCompareInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.getHistory"),
		input: SourceControlGetHistoryInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.getCommitFiles"),
		input: SourceControlGetCommitFilesInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.abortConflict"),
		input: SourceControlAbortConflictInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.createPullRequest"),
		input: SourceControlCreatePullRequestInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.getPullRequestInfo"),
		input: SourceControlProjectInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.getGhAuthStatus"),
		input: z.undefined().optional(),
	}),
	z.strictObject({
		operation: z.literal("sourceControl.generateCommitMessage"),
		input: SourceControlGenerationRequestInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.generatePullRequestFields"),
		input: SourceControlGeneratePullRequestFieldsInputSchema,
	}),
	z.strictObject({
		operation: z.literal("sourceControl.cancelGeneration"),
		input: SourceControlCancelGenerationInputSchema,
	}),
]);

export type AppRpcRequest = z.infer<typeof AppRpcRequestSchema>;
export type AppRpcOperation = AppRpcRequest["operation"];

export const AppRpcResponseSchemas = {
	"app.getVersion": AppVersionResultSchema,
	"app.openExternal": OpenExternalResultSchema,
	"project.getState": ProjectStateViewResultSchema,
	"project.createFromScratch": ProjectStateViewResultSchema,
	"project.addExistingFolder": ProjectStateViewResultSchema,
	"project.select": ProjectStateViewResultSchema,
	"project.rename": ProjectStateViewResultSchema,
	"project.remove": ProjectStateViewResultSchema,
	"project.openInFinder": ProjectStateViewResultSchema,
	"project.locateFolder": ProjectStateViewResultSchema,
	"project.setPinned": ProjectStateViewResultSchema,
	"project.getGitSettings": ProjectGitSettingsResultSchema,
	"project.setGitSettings": ProjectStateViewResultSchema,
	"project.checkAvailability": ProjectStateViewResultSchema,
	"chat.create": ProjectStateViewResultSchema,
	"chat.createStandalone": ProjectStateViewResultSchema,
	"chat.select": ProjectStateViewResultSchema,
	"chat.rename": ProjectStateViewResultSchema,
	"chat.selectStandalone": ProjectStateViewResultSchema,
	"chat.fork": ProjectStateViewResultSchema,
	"chat.clone": ProjectStateViewResultSchema,
	"chat.branch": ProjectStateViewResultSchema,
	"piSession.start": PiSessionStartResultSchema,
	"piSession.submit": PiSessionActionResultSchema,
	"piSession.abort": PiSessionActionResultSchema,
	"piSession.history": PiSessionHistoryResultSchema,
	"piSession.prepare": PiSessionStartResultSchema,
	"piSession.attach": PiSessionStartResultSchema,
	"piSession.dispose": PiSessionActionResultSchema,
	"piSession.getSettings": PiSessionSettingsResultSchema,
	"piSession.getCommands": PiSessionRuntimeCommandsResultSchema,
	"piSession.getDefaultSettings": PiSessionSettingsResultSchema,
	"piSession.setModel": PiSessionSettingsResultSchema,
	"piSession.setThinkingLevel": PiSessionSettingsResultSchema,
	"piSession.setDefaultModel": PiSessionSettingsResultSchema,
	"piSession.setDefaultThinkingLevel": PiSessionSettingsResultSchema,
	"piSession.updateQueuedMessage": PiSessionQueueResultSchema,
	"piSession.removeQueuedMessage": PiSessionQueueResultSchema,
	"workspaceFiles.listDirectory": WorkspaceListDirectoryResultSchema,
	"workspaceFiles.readFile": WorkspaceReadFileResultSchema,
	"workspaceFiles.writeFile": WorkspaceWriteFileResultSchema,
	"sourceControl.getStatus": SourceControlGetStatusResultSchema,
	"sourceControl.checkIgnored": SourceControlCheckIgnoredResultSchema,
	"sourceControl.stage": SourceControlMutationResultSchema,
	"sourceControl.unstage": SourceControlMutationResultSchema,
	"sourceControl.discard": SourceControlMutationResultSchema,
	"sourceControl.bulkStage": SourceControlMutationResultSchema,
	"sourceControl.bulkUnstage": SourceControlMutationResultSchema,
	"sourceControl.bulkDiscard": SourceControlMutationResultSchema,
	"sourceControl.initializeRepository": SourceControlMutationResultSchema,
	"sourceControl.commit": SourceControlCommitResultSchema,
	"sourceControl.getDiff": SourceControlGetDiffResultSchema,
	"sourceControl.getUpstreamStatus": SourceControlUpstreamStatusResultSchema,
	"sourceControl.fetch": SourceControlMutationResultSchema,
	"sourceControl.push": SourceControlMutationResultSchema,
	"sourceControl.forcePushWithLease": SourceControlMutationResultSchema,
	"sourceControl.pull": SourceControlMutationResultSchema,
	"sourceControl.sync": SourceControlMutationResultSchema,
	"sourceControl.fastForward": SourceControlMutationResultSchema,
	"sourceControl.publish": SourceControlMutationResultSchema,
	"sourceControl.rebaseFromBase": SourceControlMutationResultSchema,
	"sourceControl.getBranchCompare": SourceControlBranchCompareResultSchema,
	"sourceControl.getHistory": SourceControlGetHistoryResultSchema,
	"sourceControl.getCommitFiles": SourceControlGetCommitFilesResultSchema,
	"sourceControl.abortConflict": SourceControlMutationResultSchema,
	"sourceControl.createPullRequest": SourceControlPullRequestInfoResultSchema,
	"sourceControl.getPullRequestInfo": SourceControlPullRequestInfoResultSchema,
	"sourceControl.getGhAuthStatus": SourceControlGhAuthStatusResultSchema,
	"sourceControl.generateCommitMessage": SourceControlGenerateCommitMessageResultSchema,
	"sourceControl.generatePullRequestFields": SourceControlGeneratePullRequestFieldsResultSchema,
	"sourceControl.cancelGeneration": SourceControlMutationResultSchema,
} as const satisfies Record<AppRpcOperation, z.ZodTypeAny>;

export const PiSessionEventEnvelopeSchema = z.strictObject({
	type: z.literal("pi-session:event"),
	event: PiSessionEventSchema,
});

export type PiSessionEventEnvelope = z.infer<typeof PiSessionEventEnvelopeSchema>;
